### ISSUE TITLE
Missing final example from Nodevember

### ISSUE THREAD

**Issue by coryhouse** [tysoncadenhead/coffee-ratios#1]
Hi Tyson - Really enjoyed the talk! Can you please post the final demo you created today? I don't see anything matching in the existing branches. Thanks again for speaking!

**Comment by tysoncadenhead** [comment]
@coryhouse My bad! I totally forgot to push it! Here's the two versions side by side in a PR:
https://github.com/tysoncadenhead/coffee-ratios/pull/2/files
